# not needed at the moment, defined menu in hugo.yaml instead (to avoid adding the "si" to url)
si:
  languageName: Slovenian
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "&copy; DGRM {{< current_year >}}"
  title: "Društvo general Rudolf Maister Kranj"
  params:
    description: "..."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "2024 - Leto generala Rudolfa Maistra"
      link: "https://www.gov.si/zbirke/projekti-in-programi/2024-leto-generala-rudolfa-maistra/"
    footer_cta:
      text: "Join us"
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "objave"
      name: "Objave"
      url: "/objave/"
      weight: 1
    - identifier: "drustvo"
      name: "Društvo"
      url: "drustvo/"
      weight: 2
    - identifier: "o-drustvu"
      name: "O društvu"
      url: "/o-drustvu/"
      weight: 1
      post: "..."
      parent: "drustvo"
    - identifier: "statut"
      name: "Statut društva"
      url: "/statut-drustva/"
      weight: 2
      parent: "drustvo"
    - identifier: "program"
      name: "Program"
      url: "/program/"
      weight: 3
      parent: "drustvo"
    - identifier: "kontakt"
      name: "Kontakt"
      url: "/kontakt/"
      weight: 4
      parent: "drustvo"
    - identifier: "zapisniki"
      name: "Zapisniki"
      url: "/zapisniki/"
      weight: 3
      parent: "drustvo"
    - identifier: "strazarji"
      name: "Stražarji Karavank"
      url: "/strazarji-karavank/"
      weight: 3
    - identifier: "prispevki"
      name: "Prispevki in članki"
      url: "/prispevki-in-clanki/"
      weight: 4
    - identifier: "vojaski-dogodki"
      name: "Vojaški dogodki na Koroškem po koncu I. svetovne vojne"
      url: "/vojaski-dogodki-po-koncu-prve-svetovne-vojne/"
      weight: 1
      post: "..."
      parent: "prispevki"
