######################## default configuration ####################
# Your theme name
theme: "dot-org-hugo-theme"
# Title of your website (required).
title: "Društvo general Rudolf Maister Kranj"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone: "America/Los_Angeles"

######################## i18n ####################
# Auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
#hasCJKLanguage: true
# Set default content directory for multilingual
contentDir: content/
# Set fallback if international version is not available
#defaultContentLanguage: si
# Set the default language as the root rather than in folder i.e. don't use /en/
#defaultContentLanguageInSubdir: true

markup:
  goldmark:
    renderer:
      unsafe: true

######################## privacy & speed ####################
# Enable do not track, no cookies on Video embeds
privacy:
  youtube:
    privacyEnhanced: true
  vimeo:
    enableDNT: true

### copyright (markdown can be used) ###
copyright: "&copy; DGRM Kranj {{< current_year >}}"
title: "Društvo general Rudolf Maister Kranj"
params:
  description: ""
  ### accessibility ###
  ###  accessibility:
  ###    skip_text: "Skip to content"
  ###    help_text: "Accessibility Statement"
  ###    help_url: "/example-page/"
  ### calls to action ###
  main_cta:
    text: "2024 - Leto generala Rudolfa Maistra"
    link: "https://www.gov.si/zbirke/projekti-in-programi/2024-leto-generala-rudolfa-maistra/"
  footer_cta:
    text: "Kontakt"
    link: "/kontakt/"
  ### github_edit: "Edit this page on GitHub"
### example menu showing children ###
menu:
  main:
  - identifier: "objave"
    name: "Objave"
    url: "/objave/"
    weight: 1
  - identifier: "strazarji"
    name: "Stražarji Karavank"
    url: "/strazarji-karavank/"
    weight: 2
  - identifier: "prispevki"
    name: "Prispevki in članki"
    url: "/prispevki-in-clanki/"
    weight: 3
  - identifier: "spominski-zbornik"
    name: "Spominski zbornik ob 60-letnici bojev za severno slovensko mejo 1918-1919 (Maribor 1979)"
    url: "/spominski-zbornik-maribor/"
    weight: 1
    post: ""
    parent: "prispevki"
  - identifier: "jeseniski-trikot"
    name: "Lojze Ude: Jeseniški trikot - Zgodovinski časopis 33/1979"
    url: "/lojze-ude-jeseniski-trikot/"
    weight: 2
    post: ""
    parent: "prispevki"
  - identifier: "stane-bostjancic-naloga"
    name: "Stane Boštjančič: Domača naloga za zaključni izpit v gimnaziji v Kranju leta 1959 - Ob 40. obletnici koroškega plebiscita"
    url: "/stane-bostjancic-naloga/"
    weight: 3
    post: ""
    parent: "prispevki"
  - identifier: "vojaski-dogodki"
    name: "Gregor Kastelic: Vojaški dogodki na Koroškem po koncu I. svetovne vojne"
    url: "/vojaski-dogodki-po-koncu-prve-svetovne-vojne/"
    weight: 4
    post: ""
    parent: "prispevki"
  - identifier: "ravbar-porocnik-lojze-ude"
    name: "Matjaž Ravbar: Poročnik Lojze Ude - borec za slovensko severno mejo"
    url: "/ravbar-porocnik-lojze-ude/"
    weight: 5
    parent: "prispevki"
  - identifier: "lojze-ude-boji"
    name: "Lojze Ude: Boji v Rožu in Ziljski dolini leta 1918/19"
    url: "/lojze-ude-boji/"
    weight: 6
    parent: "prispevki"
  - identifier: "janez-kavar-lojze-ude"
    name: "Janez Kavar: Tržičan Lojze Ude"
    url: "/janez-kavar-lojze-ude/"
    weight: 7
    parent: "prispevki"
  - identifier: "joze-kosnjek-branili-severno-mejo"
    name: "Jože Košnjek: Na Karavankah branili severno mejo"
    url: "/joze-kosnjek-branili-severno-mejo/"
    weight: 8
    parent: "prispevki"
  - identifier: "zgornjesavc-borci-za-severno-mejo"
    name: "Matjaž Podlipnik: Zgodbe s kavča - borci za severno mejo"
    url: "/zgornjesavc-borci-za-severno-mejo/"
    weight: 9
    parent: "prispevki"
  - identifier: "lojze-ude-boj-za-maribor"
    name: "Lojze Ude: Boj za Maribor in štajersko Podravje l. 1918-19"
    url: "/lojze-ude-boj-za-maribor/"
    weight: 10
    parent: "prispevki"
  - identifier: "andrej-zemva-karel-sefman"
    name: "Andrej Žemva: Karel Šefman (1889-1973)"
    url: "/andrej-zemva-karel-sefman/"
    weight: 11
    parent: "prispevki"
  - identifier: "andrej-zemva-karel-sefman-pismoi"
    name: "Andrej Žemva: pismo Karlu Šefmanu"
    url: "/andrej-zemva-karel-sefman-pismo/"
    weight: 12
    parent: "prispevki"
  - identifier: "drustvo"
    name: "Društvo"
    url: "drustvo/"
    weight: 4
  - identifier: "o-drustvu"
    name: "O društvu"
    url: "/o-drustvu/"
    weight: 1
    parent: "drustvo"
  - identifier: "statut"
    name: "Statut društva"
    url: "/statut-drustva/"
    weight: 2
    parent: "drustvo"
  - identifier: "poslovnik"
    name: "Poslovnik društva"
    url: "/poslovnik-drustva/"
    weight: 3
    parent: "drustvo"
  - identifier: "program"
    name: "Program"
    url: "/program/"
    weight: 4
    parent: "drustvo"
  - identifier: "porocila"
    name: "Poročila"
    url: "/porocila/"
    weight: 5
    parent: "drustvo"
  - identifier: "zapisniki"
    name: "Zapisniki"
    url: "/zapisniki/"
    weight: 6
    parent: "drustvo"
  - identifier: "predlogi-za-priznanja"
    name: "Predlogi za priznanja ZDGM"
    url: "/predlogi-za-priznanja/"
    weight: 7
    parent: "drustvo"
  - identifier: "kontakt"
    name: "Kontakt"
    url: "/kontakt/"
    weight: 8
    parent: "drustvo"