en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "&copy; DGRM {{< current_year >}}"
  title: "Društvo general Rudolf Maister Kranj"
  description: "..."
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/example-page/"
    footer_cta:
      text: "Join us"
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "example"
      name: "Example"
      url: "/example-page/"
      weight: 2
    - identifier: "example-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "example"
    - identifier: "example-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "example"
    - identifier: "example-3"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "example"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "/demo-page/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5