######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/images/rudolf-maister-logo-15.png"
logo_on_black: ""
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]
showHeader: false

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/cncf/dot-org-hugo-theme"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/cloud-native-computing-foundation"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""
