
title = "Društvo general Rudolf Maister Kranj"
baseurl = "/"
relativeurls = true
languageCode = "si-sl"
theme = "dot-org-hugo-theme"
Copyright = "DGRM Kranj"

DefaultContentLanguage = "si"
Paginate = 7 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
  Description = "Društvo General Rudolf Maister Kranj, DGRM Kranj"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5